export const industryList = [
    { value: 'All industries', label: 'All industries'},
    { value: 'Agriculture, forestry and fishing', label: 'Agriculture, forestry and fishing'},
    { value: 'Mining', label: 'Mining'},
    { value: 'Manufacturing', label: 'Manufacturing'},
    { value:'Electricity, gas, water and waste services', label: 'Electricity, gas, water and waste services'},
    { value:'Construction', label: 'Construction'},
    { value:'Wholesale trade', label: 'Wholesale trade'},
    { value:'Retail trade', label: 'Retail trade'},
    { value:'Accommodation and food services', label: 'Accommodation and food services'},
    { value:' Transport, postal and warehousing', label: ' Transport, postal and warehousing'},
    { value:'Information media and telecommunications', label: 'Information media and telecommunications'},
    { value:'Financial and insurance services', label: 'Financial and insurance services'},
    { value:'Rental, hiring and real estate services', label: 'Rental, hiring and real estate services'},
    { value:'Professional, scientific and technical services', label: 'Professional, scientific and technical services'},
    { value:'Administrative and support services', label: 'Administrative and support services'},
    { value:'Public administration and safety', label: 'Public administration and safety'},
    { value:'Education and training', label: 'Education and training'},
    { value:'Health care and social assistance', label: 'Health care and social assistance'},
    { value:'Arts and recreation services', label: 'Arts and recreation services'},
    { value:'Other services', label: 'Other services'},
]