export const industryList = [
    { value: '0. All industries', label: 'All industries'},
    { value: '01. A-Agriculture, forestry and fishing', label: 'Agriculture, forestry and fishing'},
    { value: '02. B-Mining', label: 'Mining'},
    { value: '03. C-Manufacturing', label: 'Manufacturing'},
    { value: '04. D-Electricity, gas, water & waste services', label: 'Electricity, gas, water and waste services'},
    { value:'05. E-Construction', label: 'Construction'},
    { value:'06. F-Wholesale trade', label: 'Wholesale trade'},
    { value:'07. G-Retail trade', label: 'Retail trade'},
    { value:'08. H-Accommodation & food services', label: 'Accommodation and food services'},
    { value:'09. I-Transport, postal & warehousing', label: ' Transport, postal and warehousing'},
    { value:'10. J-Information media & telecommunication', label: 'Information media and telecommunications'},
    { value:'11. K-Financial & insurance services', label: 'Financial and insurance services'},
    { value:'12. L-Rental, hiring & real estate services', label: 'Rental, hiring and real estate services'},
    { value:'13. M-Professional, scientific & technical services', label: 'Professional, scientific and technical services'},
    { value:'14. N-Administrative & support services', label: 'Administrative and support services'},
    { value:'15. O-Public administration & safetyy', label: 'Public administration and safety'},
    { value:'16. P-Education & training', label: 'Education and training'},
    { value:'17. Q-Health care & social assistance', label: 'Health care and social assistance'},
    { value:'18. R-Arts & recreation services', label: 'Arts and recreation services'},
    { value:'19. S-Other services', label: 'Other services'},
]